server:
  port: 3000
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demoapi
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none
jwt:
  token:
    access-token-secret-key: aG91Mjctc2ltcGxlLXNwcmluZy1ib290LWFwaS1qd3QK
    access-token-expire-length: 300000
    refresh-token-secret-key: cmVmcmVzaHRva2Vuc2VjcmV0a2V5Cg==
    refresh-token-expire-length: 6000000
redis:
  host: localhost
  port: 6379